
export const SET_PUNTOS_TABLERO ='SET_PUNTOS_TABLERO'
export const SET_PUNTOS_JUGADOR1 ='SET_PUNTOS_JUGADOR1'
export const SET_PUNTOS_JUGADOR2 ='SET_PUNTOS_JUGADOR2'
export const RESET_PUNTOS_TABLERO ='RESET_PUNTOS_TABLERO'